
spring:
  application:
      name: jr
  datasource:
    url: jdbc:oracle:thin:@172.16.5.11:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: shr2
    password: shr2
    type: com.zaxxer.hikari.HikariDataSource





mybatis:
  configuration:
    database-id: oracle