
spring:
  application:
      name: jr
  datasource:
    url: jdbc:mysql://172.16.5.1:3306/shr?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource


mybatis:
  configuration:
    database-id: mysql





